### ISSUE TITLE
redirect_url is http instead of https when running under nginx

### ISSUE THREAD

**Issue by leon** [spring-projects/spring-social#155]
I've got a spring boot app with

```yaml
# Running behind nginx
server.tomcat:
  protocolHeader: X-Forwarded-Proto
  remoteIpHeader: X-Forwarded-For
```

But when I try to login, the redirect url for linked in starts with http instead of https.

Is there something I need to do in spring social to force https?
